### ISSUE TITLE
Selected Issue is not highlighted

### ISSUE THREAD

**Issue by aalvarado** [donkeystep/jira-dark#18]
```
ghx-selected ghx-selected-primary
```
it looks like these classes are not redefined in the css.

in the style spy I see this as the selector:

```
.ghx-issue-compact.ghx-selected, .ghx-issue-compact .ghx-selected-group
```

**Comment by aalvarado** [comment]
I was able to fix some of it by adding this to the stylesheet:

```css
body>*>*>*>*>* *:not([class^="tm-label-circle"]):not([class^="tm-status-dropdown"]):not([class^="ghx-grabber"]):not([class*="ghx-active"]):not([class*="aui-icon"]).ghx-selected .ghx-issue-content .ghx-row {
    background-color: #484848 !important;
}

body>*>*>*>*>* *:not([class^="tm-label-circle"]):not([class^="tm-status-dropdown"]):not([class^="ghx-grabber"]):not([class*="ghx-active"]):not([class*="aui-icon"]).ghx-selected .ghx-issue-content .ghx-row {

        background-color: #484848 !important;
}

body>*>*>*>*>* *:not([class^="tm-label-circle"]):not([class^="tm-status-dropdown"]):not([class^="ghx-grabber"]):not([class*="ghx-active"]):not([class*="aui-icon"]).ghx-selected .ghx-issue-content .ghx-row .ghx-type{
    background-color: #484848 !important;
}

body>*>*>*>*>* *:not([class^="tm-label-circle"]):not([class^="tm-status-dropdown"]):not([class^="ghx-grabber"]):not([class*="ghx-active"]):not([class*="aui-icon"]).ghx-selected .ghx-issue-content .ghx-row .ghx-summary {
    background-color: #484848 !important;
}

body>*>*>*>*>* *:not([class^="tm-label-circle"]):not([class^="tm-status-dropdown"]):not([class^="ghx-grabber"]):not([class*="ghx-active"]):not([class*="aui-icon"]).ghx-selected .ghx-issue-content .ghx-row .ghx-summary .ghx-inner {
    background-color: #484848 !important;
}

body>*>*>*>*>* *:not([class^="tm-label-circle"]):not([class^="tm-status-dropdown"]):not([class^="ghx-grabber"]):not([class*="ghx-active"]):not([class*="aui-icon"]).ghx-selected .ghx-issue-content {
    background-color: #484848 !important;
}
```
